[build]
builder = "DOCKERFILE"
dockerfilePath = "./harvester/Dockerfile"

[deploy]
startCommand = "sh ./harvester/run.sh"

[env]
DB_NAME = "cde"
DB_USER = "postgres"
DB_HOST_EXTERNAL = "db"
ENVIRONMENT = "development"
